databases:
  - name: medibook-db
    databaseName: medibook
    user: medibook_user
    plan: free

services:
  # 1. Spring Boot Backend
  - type: web
    name: medibook-api
    env: docker
    rootDir: backend
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: medibook-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: medibook-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: medibook-db
          property: database
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: medibook-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: medibook-db
          property: password
      - key: APP_TIMEZONE
        value: Asia/Ho_Chi_Minh
      - key: MAIL_ENABLED
        value: true
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: tnguyenanh189@gmail.com
      - key: MAIL_PASSWORD
        value: xbqqbxmdftwrguvr
      - key: MAIL_FROM
        value: Medibook Support <tnguyenanh189@gmail.com>

